name: DevOps Pipeline
on:
    push:
        branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
        strategy:
            matrix:
                node-version: [ 24.11.1 ]